version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout

  test:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout

workflows:
  maven_test:
    jobs:
      - build
      - maven/test:
          filters:
            branches:
              only:
                - master