version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout

  test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout

  upload-to-codecov:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: "Tests with JaCoCo coverage"
          command: mvn clean verify jacoco:report
      - run:
          name: "Upload to Codecov"
          command: bash <(curl -s https://codecov.io/bash)
      - codecov/upload

  checkstyle:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: "Checkstyle"
          command: mvn checkstyle:check

  create_javadoc:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: "Generate Javadoc"
          command: mvn javadoc:javadoc

  upload_javadoc:
    docker:
      - image: node:8.10.0
    steps:
      - run:
          name: "Disable jekyll builds"
          command: touch docs/_build/html/.nojekyll
      - run:
          name: "Install and configure dependencies"
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "niono235@gmail.com"
            git config user.name "blondeaupierre"
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Jdtpsofzo92QaAly7txCBrMafDvHLzcyUGVHUi2nXNE"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Update Javadoc" --dist docs/

workflows:
  maven_test:
    jobs:
      - build
      - maven/test:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - maven/test
      - checkstyle
      - create_javadoc
      - upload_javadoc:
          requires:
            - create_javadoc