version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: "Tests with JaCoCo coverage"
          command: mvn clean verify jacoco:report
      - run:
          name: "Upload Coverage Report"
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  upload-to-codecov:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build:
          jobs:
            - test